TFC_WOODS = ["acacia",
             "ash",
             "aspen",
             "birch",
             "blackwood",
             "chestnut",
             "douglas_fir",
             "hickory",
             "kapok",
             "mangrove",
             "maple",
             "oak",
             "palm",
             "pine",
             "rosewood",
             "sequoia",
             "spruce",
             "sycamore",
             "white_cedar",
             "willow"]

FLORAE_WOODS: dict[str, str] = {"african_padauk": "African Padauk",
                                "alder": "Alder",
                                "angelim": "Angelim",
                                "argyle_eucalyptus": "Argyle Eucalyptus",
                                "bald_cypress": "Bald Cypress",
                                # TODO fill out the empty strings to be translation key version of the wood name
                                "baobab": "",
                                "beech": "",
                                "black_walnut": "",
                                "black_willow": "",
                                "brazilwood": "",
                                "butternut": "",
                                "buxus": "",
                                "cocobolo": "",
                                "common_oak": "",
                                "cypress": "",
                                "ebony": "",
                                "fever": "",
                                "ghaf": "",
                                "ginkgo": "",
                                "greenheart": "",
                                "hawthorn": "",
                                "hazel": "",
                                "hemlock": "",
                                "holly": "",
                                "hornbeam": "",
                                "iroko": "",
                                "ironwood": "",
                                "jabuticabeira": "",
                                "joshua": "",
                                "juniper": "",
                                "kauri": "",
                                "larch": "",
                                "laurel": "",
                                "limba": "",
                                "locust": "",
                                "logwood": "",
                                "maclura": "",
                                "mahoe": "",
                                "mahogany": "",
                                "marblewood": "",
                                "medlar": "",
                                "messmate": "",
                                "mountain_ash": "",
                                "mulberry": "",
                                "nordmann_fir": "",
                                "norway_spruce": "",
                                "pear": "",
                                "pink_cherry_blossom": "",
                                "pink_ipe": "",
                                "pink_ivory": "",
                                "poplar": "",
                                "purple_ipe": "",
                                "purple_jacaranda": "",
                                "purpleheart": "",
                                "quince": "",
                                "rainbow_eucalyptus": "",
                                "red_cedar": "",
                                "red_cypress": "",
                                "red_elm": "",
                                "red_mangrove": "",
                                "redwood": "",
                                "rowan": "",
                                "rubber_fig": "",
                                "sloe": "",
                                "snow_gum_eucalyptus": "",
                                "sorb": "",
                                "sweetgum": "",
                                "syzygium": "",
                                "teak": "",
                                "walnut": "",
                                "wenge": "",
                                "white_cherry_blossom": "",
                                "white_elm": "",
                                "white_ipe": "",
                                "white_jacaranda": "",
                                "white_mangrove": "",
                                "whitebeam": "",
                                "yellow_ipe": "",
                                "yellow_jacaranda": "",
                                "yellow_meranti": "",
                                "yew": "",
                                "zebrawood": "",
                                "persimmon": "",
                                "bamboo": ""}


def normalize(s: str) -> str:
    """
    Takes a string like dark_oak and converts it to Dark Oak.
    Yes this method is horribly named I'm having trouble coming up with a good one :|
    """
    return ' '.join([word.capitalize() for word in s.split('_')])


DEFAULT_LANG = {
    # Entities
    **{f"entity.firmaciv.rowboat.{wood}": f"{normalize(wood)} Rowboat" for wood in TFC_WOODS},
    **{f"entity.firmaciv.sloop.{wood}": f"{normalize(wood)} Sloop" for wood in TFC_WOODS},
    **{f"entity.firmaciv.sloop_construction.{wood}": f"{normalize(wood)} Sloop" for wood in TFC_WOODS},
    **{f"entity.fimaciv.dugout_canoe.{wood}": f"{normalize(wood)} Dugout Canoe" for wood in TFC_WOODS},

    "block.firmaciv.thatch_roofing_stairs": "Angled Thatch",
    "block.firmaciv.thatch_roofing_slab": "Thatch Slab",
    "block.firmaciv.thatch_roofing": "Angled Thatch",

    "entity.firmaciv.kayak": "Kayak",

    "entity.firmaciv.compartment_tfcchest": "Chest Compartment",

    "itemGroup.firmaciv": "Firma: Civilization",
    "creativetab.firmaciv_tab": "Firma: Civilization",
    "creativetab.watercraft_tab": "Watercraft",
    "creativetab.navigation_tab": "Navigation",

    "tfc.recipe.barrel.firmaciv.barrel.large_waterproof_hide_olive": "Large Waterproof Hide",
    "tfc.recipe.barrel.firmaciv.barrel.large_waterproof_hide_tallow": "Large Waterproof Hide",

    "copy_latitude": "Copy Latitude to Clipboard",
    "copy_longitude": "Copy Longitude to Clipboard",
    "copy_latlon": "Copy Latitude and Longitude to Clipboard",
    "copy_altitude": "Copy Altitude to Clipboard",

    "latitude": "Latitude",
    "longitude": "Longitude",
    "altitude": "Altitude",
    "degrees": "Degrees",
    "sea_level": "Sea Level",
    "north": "North",
    "south": "South",
    "east": "East",
    "west": "West",
    "above": "Above",
    "below": "Below",
    "meters": "Meters",

    "press_button": "Press",
    "eject_passengers": "to eject",
    "restless_passenger": "This passenger is restless.",

    "firmaciv.advancements.kayak_paddle.title": "Double Trouble",
    "firmaciv.advancements.kayak_paddle.description": "Craft a Kayak Paddle",
    "firmaciv.advancements.canoe.title": "Burnout Paradise",
    "firmaciv.advancements.canoe.description": "Attempt to light a canoe hull",
    "firmaciv.advancements.oar.title": "Oaring my Paddleboat",
    "firmaciv.advancements.oar.description": "Craft an Oar",
    "firmaciv.advancements.kayak.title": "I'll carry you home tonight",
    "firmaciv.advancements.kayak.description": "Craft a Kayak",
    "firmaciv.advancements.nav_clock.title": "Get your time from the Admiral",
    "firmaciv.advancements.nav_clock.description": "Craft a Navigator's Timepiece",
    "firmaciv.advancements.sextant.title": "The Stars Will Aid",
    "firmaciv.advancements.sextant.description": "Craft a Sextant",
    "firmaciv.advancements.barometer.title": "Surf and/or Turf",
    "firmaciv.advancements.barometer.description": "Craft a Barometer",
    "firmaciv.advancements.oarlock.title": "The Montlake Cut",
    "firmaciv.advancements.oarlock.description": "Smith an Oarlock"
}
